export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const FORGOTPASS = 'FORGOTPASS';
export const CREATEPASS = 'CREATEPASS';
export const UPDATEUSER = 'UPDATEUSER'
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const DELETE_LOADING = 'DELETE_LOADING';
export const END_DELETE = 'END_DELETE';
export const START_CREATING = 'START_CREATING';
export const END_CREATING = 'END_CREATING';

export const START_DISPO_LOADING = 'START_DISPO_LOADING';
export const END_DISPO_LOADING = 'END_DISPO_LOADING';

export const START_BUYER_LOADING = 'START_BUYER_LOADING';
export const END_BUYER_LOADING = 'END_BUYER_LOADING';
export const DELETE_BUYER_LOADING = 'DELETE_BUYER_LOADING';
export const END_BUYER_DELETE = 'END_BUYER_DELETE';

export const ACTIVE_PROPERTIES_LOADING = 'ACTIVE_PROPERTIES_LOADING';
export const END_ACTIVE_LOADING = 'END_ACTIVE_LOADING';

export const FETCH_PROPERTY = 'FETCH_PROPERTY';

export const START_LOADING_PROP = 'START_LOADING_PROP';
export const END_LOADING_PROP = 'END_LOADING_PROP';

export const START_UPDATING = 'START_UPDATING';
export const END_UPDATING = 'END_UPDATING';

export const FETCH_BY_MARKETS ='FETCH_BY_MARKETS';
export const FETCH_ACTIVE_PROPERTY = 'FETCH_ACTIVE_PROPERTY';